---
title: 'Introduction'
teaching: 5
exercises: 0
---

:::::::::::::::::::::::::::::::::::::: questions 

- Presents the context of the lesson, in particular the UK focus
and documents were information was consulted.
- Clarifies that any specific data needs to be dealt with
in the particular context in which it is created,
and in complex cases will need of a law expert.

::::::::::::::::::::::::::::::::::::::::::::::::




This lesson presents information
that has been gathered from a mixture of
web resources, references and links:


- **British library**:
[https://www.bl.uk/business-and-ip-centre/articles/what-is-copyright](https://www.bl.uk/business-and-ip-centre/articles/what-is-copyright)
- **Jisc guides**: [https://www.jisc.ac.uk/full-guide/copyright-law](https://www.jisc.ac.uk/full-guide/copyright-law)
- **Jisc digitisation**:[https://www.jisc.ac.uk/guides/3d-digitisation-and-intellectual-property-rights](https://www.jisc.ac.uk/guides/3d-digitisation-and-intellectual-property-rights)
- **Gov.uk**: 
  - General copyright information [https://www.gov.uk/copyright](https://www.gov.uk/copyright)
  - Copyright specific to images: [https://www.gov.uk/government/publications/copyright-notice-digital-images-photographs-and-the-internet/copyright-notice-digital-images-photographs-and-the-internet](https://www.gov.uk/government/publications/copyright-notice-digital-images-photographs-and-the-internet/copyright-notice-digital-images-photographs-and-the-internet)
- **Creative Commons (CC)**: 
  - Licenses: [https://creativecommons.org/licenses/](https://creativecommons.org/licenses/)
  -  License chooser: [https://chooser-beta.creativecommons.org/](https://chooser-beta.creativecommons.org/)
- Creative Commons Corporation (2011), The Power of Open, [https://thepowerofopen.org/assets/pdfs/tpoo_eng.pdf](https://thepowerofopen.org/assets/pdfs/tpoo_eng.pdf)
- Pila, Justine, Copyright and its Categories of Original Works (July 1, 2008). Oxford Journal of Legal Studies, Vol. 30, No. 2, pp. 229–254, 2010, Oxford Legal Studies Research Paper No. 22/2008, Available at SSRN: https://ssrn.com/abstract=1160176 or [http://dx.doi.org/10.2139/ssrn.1160176](http://dx.doi.org/10.2139/ssrn.1160176)
- Wallace, Andrea. A Culture of Copyright: A scoping study on open access to digital cultural heritage collections in the UK. Research Report. Towards A National Collection, UKRI, (2022), [https://openresearch.community/documents/a-culture-of-copyright-a-wallace](https://openresearch.community/documents/a-culture-of-copyright-a-wallace)
